KEEPALIVED_COMMAND_LINE_ARGUMENTS: --log-detail --dump-conf

KEEPALIVED_INTERFACE: eth0
KEEPALIVED_ROUTER_ID: 20
KEEPALIVED_UNICAST_SRC_IP: 192.168.1.10
KEEPALIVED_PASSWORD: d0cker
KEEPALIVED_PRIORITY: 150

KEEPALIVED_UNICAST_PEERS:
  - 192.168.1.10
  - 192.168.1.11

KEEPALIVED_VIRTUAL_IPS:
  - 192.168.1.231/24
  - 192.168.1.232/24

KEEPALIVED_VIRTUAL6_IPS:
  - 2001:db8:abcd:0012:0000:0000:0000:0001/64

KEEPALIVED_NOTIFY: /container/service/keepalived/assets/notify.sh
