KEEPALIVED_COMMAND_LINE_ARGUMENTS: --log-detail --dump-conf

KEEPALIVED_INTERFACE: eth0
KEEPALIVED_ROUTER_ID: 20
KEEPALIVED_UNICAST_SRC_IP: 192.168.1.10
KEEPALIVED_PASSWORD: d0cker
KEEPALIVED_PRIORITY: 150

KEEPALIVED_UNICAST_PEERS:
  - 192.168.1.10
  - 192.168.1.11

KEEPALIVED_VIRTUAL_IPS:
  - 192.168.1.231
  - 192.168.1.232

KEEPALIVED_NOTIFY: /container/service/keepalived/assets/notify.sh
