KEEPALIVED_COMMAND_LINE_ARGUMENTS: --log-detail --dump-conf

KEEPALIVED_ETH0_INTERFACE: eth0
KEEPALIVED_ETH0_ROUTER_ID: 20
KEEPALIVED_ETH0_UNICAST_SRC_IP: 192.168.1.10
KEEPALIVED_ETH0_PASSWORD: d0cker
KEEPALIVED_ETH0_PRIORITY: 150

KEEPALIVED_ETH0_UNICAST_PEERS:
  - 192.168.1.10
  - 192.168.1.11

KEEPALIVED_ETH0_VIRTUAL_IPS:
  - 192.168.1.231
  - 192.168.1.232

KEEPALIVED_ETH1_INTERFACE: eth1
KEEPALIVED_ETH1_ROUTER_ID: 21
KEEPALIVED_ETH1_UNICAST_SRC_IP: 192.168.2.10
KEEPALIVED_ETH1_PASSWORD: d0cker
KEEPALIVED_ETH1_PRIORITY: 150

KEEPALIVED_ETH1_UNICAST_PEERS:
  - 192.168.2.10
  - 192.168.2.11

KEEPALIVED_ETH1_VIRTUAL_IPS:
  - 192.168.2.231
  - 192.168.2.232

KEEPALIVED_NOTIFY: /container/service/keepalived/assets/notify.sh
